title: Meet The Theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
favicon: assets/images/favicon.png
theme: jekyll-theme-cayman
host: 0.0.0.0
port: 5000
